/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adria
 */
public class Practica2_4 extends javax.swing.JFrame {

    /**
     * Creates new form Practica2_4
     */
    public Practica2_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        op1 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        op2 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JCheckBox();
        op5 = new javax.swing.JCheckBox();
        op6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        caja_texto_correo = new javax.swing.JTextField();
        caja_texto = new javax.swing.JTextField();
        caja_spinner = new javax.swing.JSpinner();
        caja_opciones = new javax.swing.JComboBox<>();
        barra = new javax.swing.JSlider();
        boton_onoff = new javax.swing.JToggleButton();
        op1_espejo = new javax.swing.JRadioButton();
        op2_espejo = new javax.swing.JRadioButton();
        op3_espejo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        caja_texto_correo_espejo = new javax.swing.JTextField();
        op6_espejo = new javax.swing.JCheckBox();
        op5_espejo = new javax.swing.JCheckBox();
        op4_espejo = new javax.swing.JCheckBox();
        caja_texto_espejo = new javax.swing.JTextField();
        caja_spinner_espejo = new javax.swing.JSpinner();
        caja_opciones_espejo = new javax.swing.JComboBox<>();
        boton_onoff_espejo = new javax.swing.JToggleButton();
        barra_espejo = new javax.swing.JSlider();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        op1.setText("Opción 1");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op3.setText("Opción 3");
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op2.setText("Opción 2");
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        op4.setText("Opción 4");
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        op5.setText("Opción 5");
        op5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op5ActionPerformed(evt);
            }
        });

        op6.setText("Opción 6");
        op6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Correo");

        caja_texto_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_texto_correoActionPerformed(evt);
            }
        });
        caja_texto_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_texto_correoKeyReleased(evt);
            }
        });

        caja_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_textoKeyReleased(evt);
            }
        });

        caja_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                caja_spinnerStateChanged(evt);
            }
        });
        caja_spinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caja_spinnerMouseClicked(evt);
            }
        });

        caja_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        caja_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_opcionesActionPerformed(evt);
            }
        });

        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                barraMouseReleased(evt);
            }
        });

        boton_onoff.setIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-LAALAD\\media\\b_on.png")); // NOI18N
        boton_onoff.setRolloverEnabled(false);
        boton_onoff.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-LAALAD\\media\\b_off.png")); // NOI18N
        boton_onoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_onoffActionPerformed(evt);
            }
        });

        op1_espejo.setText("Opción 1");
        op1_espejo.setEnabled(false);

        op2_espejo.setText("Opción 2");
        op2_espejo.setEnabled(false);

        op3_espejo.setText("Opción 3");
        op3_espejo.setEnabled(false);
        op3_espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3_espejoActionPerformed(evt);
            }
        });

        jLabel2.setText("Correo");
        jLabel2.setEnabled(false);

        caja_texto_correo_espejo.setEnabled(false);

        op6_espejo.setText("Opción 6");
        op6_espejo.setEnabled(false);

        op5_espejo.setText("Opción 5");
        op5_espejo.setEnabled(false);

        op4_espejo.setText("Opción 4");
        op4_espejo.setEnabled(false);

        caja_texto_espejo.setEnabled(false);

        caja_spinner_espejo.setEnabled(false);

        caja_opciones_espejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        caja_opciones_espejo.setEnabled(false);

        boton_onoff_espejo.setIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-LAALAD\\media\\b_on.png")); // NOI18N
        boton_onoff_espejo.setEnabled(false);
        boton_onoff_espejo.setRolloverEnabled(false);
        boton_onoff_espejo.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\adria\\Documents\\GitHub\\pr-ctica-2-4-elementos-interfaz-mixta-LAALAD\\media\\b_off.png")); // NOI18N
        boton_onoff_espejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_onoff_espejoActionPerformed(evt);
            }
        });

        barra_espejo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_onoff)
                .addGap(84, 84, 84))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(op1_espejo)
                                            .addComponent(op3_espejo)
                                            .addComponent(op2_espejo))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(op5_espejo)
                                            .addComponent(op6_espejo)
                                            .addComponent(op4_espejo)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(caja_texto_correo_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addComponent(caja_texto_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caja_spinner_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(caja_opciones_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(boton_onoff_espejo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(barra_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op1)
                                    .addComponent(op3)
                                    .addComponent(op2))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op5)
                                    .addComponent(op6)
                                    .addComponent(op4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(caja_texto_correo)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(caja_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1)
                    .addComponent(op4)
                    .addComponent(caja_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(op2)
                                .addComponent(op5))
                            .addComponent(barra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op3)
                            .addComponent(op6)
                            .addComponent(boton_onoff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(caja_texto_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(caja_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caja_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1_espejo)
                    .addComponent(op4_espejo)
                    .addComponent(caja_texto_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(caja_spinner_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caja_opciones_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(op2_espejo)
                                    .addComponent(op5_espejo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_onoff_espejo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(op3_espejo)
                                        .addComponent(op6_espejo))))
                            .addComponent(barra_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(caja_texto_correo_espejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        // TODO add your handling code here:        
        op3_espejo.setSelected(op3.isSelected());
    }//GEN-LAST:event_op3ActionPerformed

    private void boton_onoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_onoffActionPerformed
        boton_onoff_espejo.setSelected(boton_onoff.isSelected());
    }//GEN-LAST:event_boton_onoffActionPerformed

    private void op3_espejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3_espejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op3_espejoActionPerformed

    private void boton_onoff_espejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_onoff_espejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_onoff_espejoActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
        op1_espejo.setSelected(op1.isSelected());
    }//GEN-LAST:event_op1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        // TODO add your handling code here:        
        op2_espejo.setSelected(op2.isSelected());
    }//GEN-LAST:event_op2ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        // TODO add your handling code here:        
        op4_espejo.setSelected(op4.isSelected());
    }//GEN-LAST:event_op4ActionPerformed

    private void op5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op5ActionPerformed
        // TODO add your handling code here:
        op5_espejo.setSelected(op5.isSelected());
    }//GEN-LAST:event_op5ActionPerformed

    private void op6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op6ActionPerformed
        // TODO add your handling code here:
        op6_espejo.setSelected(op6.isSelected());
    }//GEN-LAST:event_op6ActionPerformed

    private void caja_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_opcionesActionPerformed
        // TODO add your handling code here:
        caja_opciones_espejo.setSelectedItem(caja_opciones.getSelectedItem());
    }//GEN-LAST:event_caja_opcionesActionPerformed

    private void caja_texto_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_texto_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_texto_correoActionPerformed

    private void caja_textoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_textoKeyReleased
        String texto = caja_texto.getText();
        String al_reves = "";

        for (int i = texto.length() - 1; i >= 0; i--) {
            al_reves += texto.charAt(i);
        }

        caja_texto_espejo.setText(al_reves);
    }//GEN-LAST:event_caja_textoKeyReleased

    private void caja_texto_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_texto_correoKeyReleased
      
    }//GEN-LAST:event_caja_texto_correoKeyReleased

    private void barraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseReleased
                                        
       barra_espejo.setValue(barra.getValue());
    }//GEN-LAST:event_barraMouseReleased

    private void caja_spinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja_spinnerMouseClicked
        
    }//GEN-LAST:event_caja_spinnerMouseClicked

    private void caja_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_caja_spinnerStateChanged
        caja_spinner_espejo.setValue(caja_spinner.getValue());
    }//GEN-LAST:event_caja_spinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica2_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica2_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barra;
    private javax.swing.JSlider barra_espejo;
    private javax.swing.JToggleButton boton_onoff;
    private javax.swing.JToggleButton boton_onoff_espejo;
    private javax.swing.JComboBox<String> caja_opciones;
    private javax.swing.JComboBox<String> caja_opciones_espejo;
    private javax.swing.JSpinner caja_spinner;
    private javax.swing.JSpinner caja_spinner_espejo;
    private javax.swing.JTextField caja_texto;
    private javax.swing.JTextField caja_texto_correo;
    private javax.swing.JTextField caja_texto_correo_espejo;
    private javax.swing.JTextField caja_texto_espejo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op1_espejo;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op2_espejo;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op3_espejo;
    private javax.swing.JCheckBox op4;
    private javax.swing.JCheckBox op4_espejo;
    private javax.swing.JCheckBox op5;
    private javax.swing.JCheckBox op5_espejo;
    private javax.swing.JCheckBox op6;
    private javax.swing.JCheckBox op6_espejo;
    // End of variables declaration//GEN-END:variables
}
